FORMAT: 1A
HOST: https://nicolopomini-lostfound.herokuapp.com/

# Lost & Found

API per segnalare un oggetto che hai smarrito o che hai ritrovato

## Segnalare un oggetto smarrito [/issues/search{?descrizione,aula,data}]

### Segnala oggetto smarrito [GET]

+ Parameters
    + descrizione - Descrizione testuale dell'oggetto trovato
    + aula (optional) - Aula in cui l'oggetto è stato trovato
    + data (optional) - Data nella quale l'oggetto è stato trovato

+ Response 200 (application/json)

        {
            "error" : "false",
            "issue" : "507f1f77bcf86cd799439011"
        }

## Segnalare un oggetto trovato [/issues/found{?descrizione,aula,data}]

### Segnala oggetto trovato [GET]

+ Parameters
    + descrizione - Descrizione testuale dell'oggetto trovato
    + aula (optional) - Aula in cui l'oggetto è stato trovato
    + data (optional) - Data nella quale l'oggetto è stato trovato

+ Response 200 (application/json)

        {
            "error" : "false",
            "issue" : "507f1f24bcf86cd593319107"
        }

## Cercare segnalazioni corrispondenti ad una issue [/issues/{issueid}]

### Cerca issues [GET]
+ Parameters
    + issueid - A valid issue id

+ Response 200 (application/json)

        {
            "error" : "false",
            "issues": 
            [
                {
                    "description" : "I found a black Rayban sunglasses.",
                    "room" : "A105",
                    "time" : "2017-11-27",
                    "inserted" : "2017-12-4",
                    "author" : {
                        "?" : "???"
                    }
                }
            ]
        }