FORMAT: 1A
HOST: https://nicolopomini-lostfound.herokuapp.com/

# Lost & Found

API per segnalare un oggetto che hai smarrito o che hai ritrovato

## Segnalare un oggetto smarrito [/issues/search{?token,description,room,time}]

### Segnala oggetto smarrito [POST]

+ Parameters
    + token - ID dell'utente che utilizza il servizio
    + description - Descrizione testuale dell'oggetto trovato
    + room (optional) - Aula in cui l'oggetto è stato trovato
    + time (optional) - Data nella quale l'oggetto è stato trovato

+ Response 200 (application/json)

        {
            "error" : "false",
            "issue" : "507f1f77bcf86cd799439011"
        }

+ Response 200 (application/json)

        {
            "error" : "Parametri non validi.",
            "issue" : null
        }

## Segnalare un oggetto trovato [/issues/found{?token,description,room,time}]

### Segnala oggetto trovato [POST]

+ Parameters
    + token - ID dell'utente che utilizza il servizio
    + description - Descrizione testuale dell'oggetto trovato
    + room (optional) - Aula in cui l'oggetto è stato trovato
    + time (optional) - Data nella quale l'oggetto è stato trovato

+ Response 200 (application/json)

        {
            "error" : "false",
            "issue" : "507f1f24bcf86cd593319107"
        }

+ Response 200 (application/json)

        {
            "error" : "Parametri non validi.",
            "issue" : null
        }

## Cercare segnalazioni corrispondenti ad una issue [/issues/{issueid}{?token}]

### Cerca issues [GET]
+ Parameters
    + issueid - A valid issue id
    + token - ID dell'utente che utilizza il servizio

+ Response 200 (application/json)

        {
            "error" : "false",
            "issues": 
            [
                {
                    "description" : "I found a black Rayban sunglasses.",
                    "room" : "A105",
                    "time" : "2017-11-27",
                    "inserted" : "2017-12-4",
                    "author" : {
                        "id" : "613457248818606593319107",
                        "name" : "Fausto Giunchiglia",
                        "email" : "fausto.giunchiglia@unitn.it"
                    }
                },
                {
                    "description" : "White iPhone X cover and Apple AirPods",
                    "room" : "",
                    "time" : "",
                    "inserted" : "2017-12-4",
                    "author" : {
                        "id" : "613457248818606593319107",
                        "name" : "Fausto Giunchiglia",
                        "email" : "fausto.giunchiglia@unitn.it"
                    }
                }
            ]
        }

+ Response 200 (application/json)

        {
            "error" : "La issue richiesta non esiste.",
            "issue" : null
        }